// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load the base .env first (shared defaults)
config();

// Then override with environment-specific file based on APP_ENV
const appEnv = process.env["APP_ENV"] || "local";
const envFiles: Record<string, string> = {
  local: ".env.local",
  test: ".env.test",
  prod: ".env.prod",
};
const envFile = envFiles[appEnv];
if (envFile) {
  config({ path: envFile, override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
